create or replace package autono_stmt_gen_test
is
  procedure
  invoke_gen_con_stmt_tbls(
      p_statement_cycle_nme IN VARCHAR2
    , p_customer_nbr        IN VARCHAR2
    , p_stmt_as_of_date     IN VARCHAR2
    , p_debug_flag          IN VARCHAR2  
  )
  ;
end;

create or replace package body autono_stmt_gen_test
is
  procedure
  invoke_gen_con_stmt_tbls(
      p_statement_cycle_nme IN VARCHAR2
    , p_customer_nbr        IN VARCHAR2
    , p_stmt_as_of_date     IN VARCHAR2
    , p_debug_flag          IN VARCHAR2  
  )
  is
    -- We require a mechanism to invoke the 
    --   lwx_ar_invo_stmt_print.Generate_Con_Stmt
    -- procedure, and generate some data with it, and then
    -- to save those data to the above "tst" tables 
    -- in the rstewar schema in an autonomous
    -- transaction so that the data generated by the
    -- call to
    --   lwx_ar_invo_stmt_print.Generate_Con_Stmt
    -- can be rolled back.
  begin
    null;
  end;
end autono_stmt_gen_test;
