/*
At present, we must create this inside the apps schema,
since my user schema, rstewar, doesn't have the 
create or replace package privilege...
*/
create or replace package autono_stmt_gen_test
is
  procedure
  invoke_gen_con_stmt_tbls(
      p_statement_cycle_nme IN VARCHAR2
    , p_customer_nbr        IN VARCHAR2
    , p_stmt_as_of_date     IN VARCHAR2
    , p_debug_flag          IN VARCHAR2  
  )
  ;
  procedure
  copy_stmt_data(p_send_to_cust_nbr varchar2, statement_cycle_id varchar2)
  ;
end;

create or replace package body autono_stmt_gen_test
is
  procedure
  invoke_gen_con_stmt_tbls(
      p_statement_cycle_nme IN VARCHAR2  -- REQUIRED
    --
    -- Need to supply this to keep it "narrowed":
    , p_customer_nbr        IN VARCHAR2  
    --
    -- This is best supplied as well, as the program will otherwise
    -- derive its own default:
    , p_stmt_as_of_date     IN VARCHAR2
    -- 
    , p_debug_flag          IN VARCHAR2  
  )
  is
    -- We require a mechanism to invoke the 
    --   lwx_ar_invo_stmt_print.Generate_Con_Stmt
    -- procedure, and generate some data with it, and then
    -- to save those data to the above "tst" tables 
    -- in the rstewar schema in an autonomous
    -- transaction so that the data generated by the
    -- call to
    --   lwx_ar_invo_stmt_print.Generate_Con_Stmt
    -- can be rolled back.
  begin
    null;
  end;
  --
  -- We must copy by identifying the header-record's
  -- requisite:
  --   send_to_cust_nbr ::=  a copy of the account number that was passed in, the p_customer_nbr
  --   statement_cycle_id ::=  a copy of the p_statement_cycle_nme parameter, I believe...
  --   
  procedure
  copy_stmt_data(p_send_to_cust_nbr varchar2, statement_cycle_id varchar2)
  is
    pragma autonomous_transaction;
  begin
    null;
  end;
  --
end autono_stmt_gen_test;
